version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: cine_tora_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cine_tora_development

volumes:
  postgres_data: