default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: cine_tora_development

test:
  <<: *default
  database: cine_tora_test

production:
  <<: *default
  database: cine_tora_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>